// concert-related
export const CONCERT_REQUEST_SUCCESSFUL = "CONCERT_REQUEST_SUCCESSFUL";
export const CONCERT_REQUEST_CREATED = "CONCERT_REQUEST_CREATED";
export const CONCERT_REQUEST_FAILED = "CONCERT_REQUEST_FAILED";

// sport-related
export const SPORT_REQUEST_SUCCESSFUL = "SPORT_REQUEST_SUCCESSFUL";
export const SPORT_REQUEST_SUCCESSFUL_ENDPOINT = "SPORT_REQUEST_SUCCESSFUL_ENDPOINTS";
export const SPORT_REQUEST_CREATED = "SPORT_REQUEST_CREATED";
export const SPORT_REQUEST_FAILED = "SPORT_REQUEST_FAILED";

// Flights-related
export const ARRIVALS_REQUEST_SUCCESSFUL = "ARRIVALS_REQUEST_SUCCESSFUL";
export const DEPARTURES_REQUEST_SUCCESSFUL = "DEPARTURES_REQUEST_SUCCESSFUL";
export const FLIGHTS_REQUEST_CREATED = "FLIGHTS_REQUEST_CREATED";
export const FLIGHTS_REQUEST_FAILED = "FLIGHTS_REQUEST_FAILED";

//bus-related
export const GET_BUSES = "GET_BUSES";
export const GET_BUSES_FULFILLED = "GET_BUSES_FULFILLED";
export const GET_BUSES_REJECTED = "GET_BUSES_REJECTED";

// Carpooling-related
export const CARPOOLING_REQUEST_SUCCESSFUL = "CARPOOLING_REQUEST_SUCCESSFUL";
export const CARPOOLING_REQUEST_CREATED = "CARPOOLING_REQUEST_CREATED";
export const CARPOOLING_REQUEST_FAILED = "CARPOOLING_REQUEST_FAILED";