// Concert
export const GET_CONCERTS = 'GET_CONCERTS';
export const GET_CONCERTS_FULFILLED = 'GET_CONCERTS_FULFILLED';
export const GET_CONCERTS_REJECTED = 'GET_CONCERTS_REJECTED';

// sport-related
export const SPORT_REQUEST_SUCCESSFUL = 'SPORT_REQUEST_SUCCESSFUL';
export const SPORT_REQUEST_SUCCESSFUL_ENDPOINT = 'SPORT_REQUEST_SUCCESSFUL_ENDPOINTS';
export const SPORT_REQUEST_CREATED = 'SPORT_REQUEST_CREATED';
export const SPORT_REQUEST_FAILED = 'SPORT_REQUEST_FAILED';

// Flights-related
export const GET_ARRIVALS = 'GET_ARRIVALS';
export const GET_ARRIVALS_FULFILLED = 'GET_ARRIVALS_FULFILLED';
export const GET_ARRIVALS_REJECTED = 'GET_ARRIVALS_REJECTED';
export const GET_DEPARTURES = 'GET_DEPARTURES';
export const GET_DEPARTURES_FULFILLED = 'GET_DEPARTURES_FULFILLED';
export const GET_DEPARTURES_REJECTED = 'GET_DEPARTURES_REJECTED';

// Buses
export const GET_BUSES = 'GET_BUSES';
export const GET_BUSES_FULFILLED = 'GET_BUSES_FULFILLED';
export const GET_BUSES_REJECTED = 'GET_BUSES_REJECTED';

// Carpooling
export const GET_DRIVERS = 'GET_DRIVERS';
export const GET_DRIVERS_FULFILLED = 'GET_DRIVERS_FULFILLED';
export const GET_DRIVERS_REJECTED = 'GET_DRIVERS_REJECTED';

// UserLogin
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_FULFILLED = 'LOGIN_USER_FULFILLED';
export const LOGIN_USER_REJECTED = 'LOGIN_USER_REJECTED';
