// concert-related
export const CONCERT_REQUEST_SUCCESSFUL = "CONCERT_REQUEST_SUCCESSFUL";
export const CONCERT_REQUEST_CREATED = "CONCERT_REQUEST_CREATED";
export const CONCERT_REQUEST_FAILED = "CONCERT_REQUEST_FAILED";
