// concert-related
export const CONCERT_REQUEST_SUCCESSFUL = "CONCERT_REQUEST_SUCCESSFUL";
export const CONCERT_REQUEST_CREATED = "CONCERT_REQUEST_CREATED";
export const CONCERT_REQUEST_FAILED = "CONCERT_REQUEST_FAILED";

// sport-related
export const SPORT_REQUEST_SUCCESSFUL = "SPORT_REQUEST_SUCCESSFUL";
export const SPORT_REQUEST_SUCCESSFUL_ENDPOINT = "SPORT_REQUEST_SUCCESSFUL_ENDPOINTS";
export const SPORT_REQUEST_CREATED = "SPORT_REQUEST_CREATED";
export const SPORT_REQUEST_FAILED = "SPORT_REQUEST_FAILED";

// flights-related
export const ARRIVALS_REQUEST_SUCCESSFUL = "ARRIVALS_REQUEST_SUCCESSFUL";
export const DEPARTURES_REQUEST_SUCCESSFUL = "DEPARTURES_REQUEST_SUCCESSFUL";
export const FLIGHTS_REQUEST_CREATED = "FLIGHTS_REQUEST_CREATED";
export const FLIGHTS_REQUEST_FAILED = "FLIGHTS_REQUEST_FAILED";

//bus-related
export const BUSES_REQUEST_SUCCESSFUL = "BUSES_REQUEST_SUCCESSFUL";
export const BUSES_REQUEST_CREATED = "BUSES_REQUEST_CREATED";
export const BUSES_REQUEST_FAILED = "BUSES_REQUEST_FAILED";