// concert-related
export const CONCERT_REQUEST_SUCCESSFUL = "CONCERT_REQUEST_SUCCESSFUL";
export const CONCERT_REQUEST_CREATED = "CONCERT_REQUEST_CREATED";
export const CONCERT_REQUEST_FAILED = "CONCERT_REQUEST_FAILED";

// sport-related
export const SPORT_REQUEST_SUCCESSFUL = "SPORT_REQUEST_SUCCESSFUL";
export const SPORT_REQUEST_CREATED = "SPORT_REQUEST_CREATED";
export const SPORT_REQUEST_FAILED = "SPORT_REQUEST_FAILED";